---
output: 
  html_document: 
    keep_md: yes
---
<h3>Process</h3>

<u>Feature 1</u>:
I decided to start by adding the BC liquor logo to the shiny webpage. This step was not too difficult but adds some visual appeal to the webpage. It is best viewed when the webpage is maximized to fill the whole screen.

<u>Feature 2</u>:
The histogram has been programmed so that the user can change its color. This gives the user the sense that they are really interacting with the app while at the same time giving a little more color and excitement to the webpage.

<u>Feature 3</u>:
The histogram and plot now each have their own tab (labeled "Histogram" and "Plot", respectively). The code for this generated substantial errors which have been fixed as a result of help from the course RAs. Segmenting the histogram and plot into separate tabs frees up visual space on the webpage, serving both a functional and an aesthetic purpose. 


Throughout this assignment I made use of <a href=https://www.youtube.com/channel/UCbck9jjLpwj7U6HHNps_9Gw>Abhinav Agrawal's shiny tutorials.</a> 

As mentioned, I relied on the help of the course RAs to troubleshoot coding issues related to setting up tabs for the shiny app.

I also used Jenny's detailed shiny tutorial to get started.

Overall I enjoyed learning the shiny app and can see myself using it in the future.

















